# Assignment 2 Data science AMIT 

In [2]:
import numpy as np 

Q1-Write a NumPy program to test whether none of the elements of a given array is zero.


In [4]:
arr=np.array([[0,2],[3,4]])
print(np.all(arr))

False


Q2-Write a NumPy program to test whether any of the elements of a given array is non-zero

In [6]:
arr2 = np.array([0,0,0,0,1])
print(np.any(arr2))

True


Q3-Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given

In [9]:
array1 = np.array([1,2,3])
array2 = np.array([1,2,3])
#a-equal
print(np.equal(array1,array2))
#b-equal within a tolerance
print(np.allclose(array1,array2))

[ True  True  True]
True


Q4-Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [12]:
#10 zeros
a1=np.zeros(10)
#10 ones
a2=np.ones(10)
#10 fives
a3=np.ones(10)*5
#
final_array=np.array([a1,a2,a3])
print(final_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


Q5-Write a NumPy program to create an array of the integers from 30 to70.

In [15]:
int_array=np.arange(30,71)
print(int_array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Q6-Write a NumPy program to create a 3x3 identity matrix

In [16]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q7-Write a NumPy program to generate a random number between 0 and 1

In [18]:
random_num = np.random.normal(0,1)
print(random_num)

0.1776193184397555


Q8-Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [20]:
random_array=np.random.normal(0,1,15)
print(random_array)

[ 0.0905146  -0.53011708 -1.69036464 -1.83252842 -1.28931186 -1.45535165
  0.56108169  1.87117968  1.03289834 -0.12019349  1.01067943  1.82484911
 -0.60511972  0.9987859   0.35027244]


Q9-Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [22]:
start=15
end=55
rang_vector = np.arange(start+1,end)
print(rang_vector)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Q10-Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [23]:
arb_int=np.random.randint(0,11,5)
print(arb_int)

[9 3 4 4 0]


Q11-Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [27]:
matrix10=np.ones((10,10))
matrix10[1:9 , 1:9] = 0 # or matrix10[1:-1 , 1:-1] = 0 
print(matrix10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q12-Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,3, 4, 5.

In [32]:
diagonal_matrix=np.diag([1,2,3,4,5])
print(diagonal_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Q13-Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [38]:
matrix4=np.zeros((4,4))

matrix4[::2 ,1::2]=1
matrix4[1::2,::2]=1
print(matrix4)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


Q14-Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [6]:
import os
x=[1,2,3,4]
y=[5,6,7,8]
print(f'originals are: {x} and {y}')
np.savez('amit.npz', x=x, y=y)
with np.load('amit.npz') as data:
    new_x = data['x']
    new_y = data['y']
    print(f'{new_x} {new_y} are the arrays after loading in the file')

originals are: [1, 2, 3, 4] and [5, 6, 7, 8]
[1 2 3 4] [5 6 7 8] are the arrays after loading in the file


Q15-Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [7]:
np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


Q16-Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number

In [9]:
my_nums=[[5.54, 3.38, 7.99],
         [3.54, 4.38, 6.99],
         [1.54, 2.39, 9.29]]
nums = np.array(my_nums)
print("Original array:")
print(nums)
n = int(input("\nEnter the comparing number:"))
print("\nElements of the said array greater than",n)
print(nums[nums > n])
print("\nElements of the said array less than",n)
print(nums[nums < n])

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Enter the comparing number:5

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 5
[3.38 3.54 4.38 1.54 2.39]
